// OTOMATİK ÜRETİLDİ (CoinGecko top-100 + Yahoo doğrulama). İlk 100 kripto (USD).
// Yeniden üretmek için: node _gen_crypto.mjs
export default [
  { ticker: "BTC", name: "Bitcoin", symbol: "BTC-USD" },
  { ticker: "ETH", name: "Ethereum", symbol: "ETH-USD" },
  { ticker: "USDT", name: "Tether", symbol: "USDT-USD" },
  { ticker: "BNB", name: "BNB", symbol: "BNB-USD" },
  { ticker: "USDC", name: "USDC", symbol: "USDC-USD" },
  { ticker: "XRP", name: "XRP", symbol: "XRP-USD" },
  { ticker: "SOL", name: "Solana", symbol: "SOL-USD" },
  { ticker: "TRX", name: "TRON", symbol: "TRX-USD" },
  { ticker: "WBT", name: "WhiteBIT Coin", symbol: "WBT-USD" },
  { ticker: "HYPE", name: "Hyperliquid", symbol: "HYPE-USD" },
  { ticker: "DOGE", name: "Dogecoin", symbol: "DOGE-USD" },
  { ticker: "USDS", name: "USDS", symbol: "USDS-USD" },
  { ticker: "RAIN", name: "Rain", symbol: "RAIN-USD" },
  { ticker: "LEO", name: "LEO Token", symbol: "LEO-USD" },
  { ticker: "ZEC", name: "Zcash", symbol: "ZEC-USD" },
  { ticker: "XMR", name: "Monero", symbol: "XMR-USD" },
  { ticker: "XLM", name: "Stellar", symbol: "XLM-USD" },
  { ticker: "ADA", name: "Cardano", symbol: "ADA-USD" },
  { ticker: "CC", name: "Canton", symbol: "CC-USD" },
  { ticker: "DAI", name: "Dai", symbol: "DAI-USD" },
  { ticker: "BCH", name: "Bitcoin Cash", symbol: "BCH-USD" },
  { ticker: "USD1", name: "USD1", symbol: "USD1-USD" },
  { ticker: "GRAM", name: "Gram (prev. Toncoin)", symbol: "GRAM-USD" },
  { ticker: "USDE", name: "Ethena USDe", symbol: "USDE-USD" },
  { ticker: "LTC", name: "Litecoin", symbol: "LTC-USD" },
  { ticker: "USDG", name: "Global Dollar", symbol: "USDG-USD" },
  { ticker: "HBAR", name: "Hedera", symbol: "HBAR-USD" },
  { ticker: "SHIB", name: "Shiba Inu", symbol: "SHIB-USD" },
  { ticker: "SUI", name: "Sui", symbol: "SUI-USD" },
  { ticker: "AVAX", name: "Avalanche", symbol: "AVAX-USD" },
  { ticker: "CRO", name: "Cronos", symbol: "CRO-USD" },
  { ticker: "PYUSD", name: "PayPal USD", symbol: "PYUSD-USD" },
  { ticker: "BUIDL", name: "BlackRock USD Institutional Digital Liquidity Fund", symbol: "BUIDL-USD" },
  { ticker: "XAUT", name: "Tether Gold", symbol: "XAUT-USD" },
  { ticker: "UNI", name: "Uniswap", symbol: "UNI-USD" },
  { ticker: "NEAR", name: "NEAR Protocol", symbol: "NEAR-USD" },
  { ticker: "USDY", name: "Ondo US Dollar Yield", symbol: "USDY-USD" },
  { ticker: "ONDO", name: "Ondo", symbol: "ONDO-USD" },
  { ticker: "TAO", name: "Bittensor", symbol: "TAO-USD" },
  { ticker: "PAXG", name: "PAX Gold", symbol: "PAXG-USD" },
  { ticker: "OKB", name: "OKB", symbol: "OKB-USD" },
  { ticker: "WLFI", name: "World Liberty Financial", symbol: "WLFI-USD" },
  { ticker: "ASTER", name: "Aster", symbol: "ASTER-USD" },
  { ticker: "HTX", name: "HTX DAO", symbol: "HTX-USD" },
  { ticker: "RLUSD", name: "Ripple USD", symbol: "RLUSD-USD" },
  { ticker: "AAVE", name: "Aave", symbol: "AAVE-USD" },
  { ticker: "USDD", name: "USDD", symbol: "USDD-USD" },
  { ticker: "USDF", name: "Falcon USD", symbol: "USDF-USD" },
  { ticker: "DOT", name: "Polkadot", symbol: "DOT-USD" },
  { ticker: "MNT", name: "Mantle", symbol: "MNT-USD" },
  { ticker: "SKY", name: "Sky", symbol: "SKY-USD" },
  { ticker: "BFUSD", name: "BFUSD", symbol: "BFUSD-USD" },
  { ticker: "WLD", name: "Worldcoin", symbol: "WLD-USD" },
  { ticker: "MORPHO", name: "Morpho", symbol: "MORPHO-USD" },
  { ticker: "BEAT", name: "Audiera", symbol: "BEAT-USD" },
  { ticker: "PEPE", name: "Pepe", symbol: "PEPE-USD" },
  { ticker: "ICP", name: "Internet Computer", symbol: "ICP-USD" },
  { ticker: "BGB", name: "Bitget Token", symbol: "BGB-USD" },
  { ticker: "USDGO", name: "USDGO", symbol: "USDGO-USD" },
  { ticker: "ETC", name: "Ethereum Classic", symbol: "ETC-USD" },
  { ticker: "STABLE", name: "​​Stable", symbol: "STABLE-USD" },
  { ticker: "KCS", name: "KuCoin", symbol: "KCS-USD" },
  { ticker: "QNT", name: "Quant", symbol: "QNT-USD" },
  { ticker: "PI", name: "Pi Network", symbol: "PI-USD" },
  { ticker: "ENA", name: "Ethena", symbol: "ENA-USD" },
  { ticker: "JST", name: "JUST", symbol: "JST-USD" },
  { ticker: "POL", name: "POL (ex-MATIC)", symbol: "POL-USD" },
  { ticker: "KAS", name: "Kaspa", symbol: "KAS-USD" },
  { ticker: "RENDER", name: "Render", symbol: "RENDER-USD" },
  { ticker: "ALGO", name: "Algorand", symbol: "ALGO-USD" },
  { ticker: "NEXO", name: "NEXO", symbol: "NEXO-USD" },
  { ticker: "ATOM", name: "Cosmos Hub", symbol: "ATOM-USD" },
  { ticker: "GT", name: "Gate", symbol: "GT-USD" },
  { ticker: "BDX", name: "Beldex", symbol: "BDX-USD" },
  { ticker: "GHO", name: "GHO", symbol: "GHO-USD" },
  { ticker: "VVV", name: "Venice Token", symbol: "VVV-USD" },
  { ticker: "JUP", name: "Jupiter", symbol: "JUP-USD" },
  { ticker: "FIL", name: "Filecoin", symbol: "FIL-USD" },
  { ticker: "YLDS", name: "YLDS", symbol: "YLDS-USD" },
  { ticker: "LIT", name: "Lighter", symbol: "LIT-USD" },
  { ticker: "XDC", name: "XDC Network", symbol: "XDC-USD" },
  { ticker: "FLR", name: "Flare", symbol: "FLR-USD" },
  { ticker: "USD0", name: "Usual USD", symbol: "USD0-USD" },
  { ticker: "ARB", name: "Arbitrum", symbol: "ARB-USD" },
  { ticker: "APT", name: "Aptos", symbol: "APT-USD" },
  { ticker: "USX", name: "USX", symbol: "USX-USD" },
  { ticker: "TUSD", name: "TrueUSD", symbol: "TUSD-USD" },
  { ticker: "INJ", name: "Injective", symbol: "INJ-USD" },
];
