// OTOMATİK ÜRETİLDİ (finans.mynet.com hisse listesi). BIST 30/50/100 dışı hisseler.
// Yeniden üretmek için: node _gen_others.mjs
export default [
  { ticker: "A1CAP", name: "A1 Capital Yatirim" },
  { ticker: "A1YEN", name: "A1 Yenilenebilir Enerji" },
  { ticker: "AAGYO", name: "Agaoglu GMYO" },
  { ticker: "ACSEL", name: "Acipayam Seluloz" },
  { ticker: "ADEL", name: "Adel Kalemcilik" },
  { ticker: "ADESE", name: "Adese Gayrimenkul" },
  { ticker: "ADGYO", name: "Adra GMYO" },
  { ticker: "AFYON", name: "Afyon Cimento" },
  { ticker: "AGESA", name: "Agesa Hayat Emeklilik" },
  { ticker: "AGHOL", name: "Anadolu Grubu Holding" },
  { ticker: "AGROT", name: "Agrotech Teknoloji" },
  { ticker: "AGYO", name: "Atakule GMYO" },
  { ticker: "AHGAZ", name: "Ahlatci Dogalgaz" },
  { ticker: "AHSGY", name: "Ahes GMYO" },
  { ticker: "AKCNS", name: "Akcansa" },
  { ticker: "AKENR", name: "Akenerji" },
  { ticker: "AKFGY", name: "Akfen GMYO" },
  { ticker: "AKFIS", name: "Akfen Insaat" },
  { ticker: "AKFYE", name: "Akfen Yen Enerji" },
  { ticker: "AKGRT", name: "Aksigorta" },
  { ticker: "AKHAN", name: "Akhan Un" },
  { ticker: "AKMGY", name: "Akmerkez GMYO" },
  { ticker: "AKSGY", name: "Akis GMYO" },
  { ticker: "AKSUE", name: "Aksu Enerji" },
  { ticker: "AKYHO", name: "Akdeniz Yatirim Holding" },
  { ticker: "ALBRK", name: "Albaraka Turk" },
  { ticker: "ALCAR", name: "Alarko Carrier" },
  { ticker: "ALCTL", name: "Alcatel Lucent Teletas" },
  { ticker: "ALFAS", name: "Alfa Solar Enerji" },
  { ticker: "ALGYO", name: "Alarko GMYO" },
  { ticker: "ALKA", name: "Alkim Kagit" },
  { ticker: "ALKIM", name: "Alkim Kimya" },
  { ticker: "ALKLC", name: "Altinkilic Gida Ve Sut" },
  { ticker: "ALTINS1", name: "Darphane Altin Sertifikasi" },
  { ticker: "ALVES", name: "Alves Kablo" },
  { ticker: "ANELE", name: "Anel Elektrik" },
  { ticker: "ANGEN", name: "Anatolia Tani Ve Biyoteknoloji" },
  { ticker: "ANHYT", name: "Anadolu Hayat Emek" },
  { ticker: "ARASE", name: "Dogu Aras Enerji" },
  { ticker: "ARDYZ", name: "Ard Bilisim Teknolojileri" },
  { ticker: "ARENA", name: "Arena Bilgisayar" },
  { ticker: "ARFYE", name: "Arf Bio Yenilenebilir Enerji" },
  { ticker: "ARMGD", name: "Armada Gida" },
  { ticker: "ARSAN", name: "Arsan Holding" },
  { ticker: "ARTMS", name: "Artemis Hali" },
  { ticker: "ARZUM", name: "Arzum Ev Aletleri" },
  { ticker: "ASGYO", name: "Asce GMYO" },
  { ticker: "ASUZU", name: "Anadolu Isuzu" },
  { ticker: "ATAGY", name: "Ata GMYO" },
  { ticker: "ATAKP", name: "Atakey Patates" },
  { ticker: "ATATP", name: "Atp Yazilim" },
  { ticker: "ATATR", name: "Ata Turizm" },
  { ticker: "ATEKS", name: "Akin Tekstil" },
  { ticker: "ATLAS", name: "Atlas Yat Ort" },
  { ticker: "ATSYH", name: "Atlantis Yatirim Holding" },
  { ticker: "AVGYO", name: "Avrasya GMYO" },
  { ticker: "AVHOL", name: "Avrupa Yatirim Holding" },
  { ticker: "AVOD", name: "Avod Gida Ve Tarim" },
  { ticker: "AVPGY", name: "Avrupakent GMYO" },
  { ticker: "AVTUR", name: "Avrasya Petrol Ve Tur" },
  { ticker: "AYCES", name: "Altinyunus Cesme" },
  { ticker: "AYDEM", name: "Aydem Enerji" },
  { ticker: "AYEN", name: "Ayen Enerji" },
  { ticker: "AYES", name: "Ayes Celik Hasir Ve Cit" },
  { ticker: "AYGAZ", name: "Aygaz" },
  { ticker: "AZTEK", name: "Aztek Teknoloji" },
  { ticker: "BAGFS", name: "Bagfas" },
  { ticker: "BAHKM", name: "Bahadir Kimya" },
  { ticker: "BAKAB", name: "Bak Ambalaj" },
  { ticker: "BALAT", name: "Balatacilar Balatacilik" },
  { ticker: "BANVT", name: "Banvit" },
  { ticker: "BARMA", name: "Barem Ambalaj" },
  { ticker: "BASCM", name: "Bastas Baskent Cimento" },
  { ticker: "BASGZ", name: "Baskent Dogalgaz GMYO" },
  { ticker: "BAYRK", name: "Bayrak Taban Sanayi" },
  { ticker: "BEGYO", name: "Bati Ege GMYO" },
  { ticker: "BESLR", name: "Besler Gida" },
  { ticker: "BESTE", name: "Best Brands Enerji" },
  { ticker: "BETAE", name: "Beta Enerji Ve Teknoloji" },
  { ticker: "BEYAZ", name: "Beyaz Filo" },
  { ticker: "BFREN", name: "Bosch Fren Sistemleri" },
  { ticker: "BIENY", name: "Bien Yapi Urunleri" },
  { ticker: "BIGCH", name: "Buyuk Sefler Bigchefs" },
  { ticker: "BIGEN", name: "Birlesim Grup Enerji" },
  { ticker: "BIGTK", name: "Big Medya Teknoloji" },
  { ticker: "BINBN", name: "Bin Ulasim Teknolojileri" },
  { ticker: "BINHO", name: "1000 Yatirimlar Hol" },
  { ticker: "BIOEN", name: "Biotrend Cevre Ve Enerji" },
  { ticker: "BIZIM", name: "Bizim Magazalari" },
  { ticker: "BJKAS", name: "Besiktas Futbol Yat" },
  { ticker: "BLCYT", name: "Bilici Yatirim" },
  { ticker: "BLUME", name: "Blume Metal Kimya" },
  { ticker: "BMSCH", name: "Bms Celik Hasir" },
  { ticker: "BMSTL", name: "Bms Birlesik Metal" },
  { ticker: "BNTAS", name: "Bantas Ambalaj" },
  { ticker: "BOBET", name: "Bogazici Beton Sanayi" },
  { ticker: "BORLS", name: "Borlease Otomotiv" },
  { ticker: "BORSK", name: "Bor Seker" },
  { ticker: "BOSSA", name: "Bossa" },
  { ticker: "BRISA", name: "Brisa" },
  { ticker: "BRKO", name: "Birko Mensucat" },
  { ticker: "BRKSN", name: "Berkosan Yalitim" },
  { ticker: "BRKVY", name: "Birikim Varlik Yonetim" },
  { ticker: "BRLSM", name: "Birlesim Muhendislik" },
  { ticker: "BRMEN", name: "Birlik Mensucat" },
  { ticker: "BUCIM", name: "Bursa Cimento" },
  { ticker: "BULGS", name: "Bulls Gsyo" },
  { ticker: "BURCE", name: "Burcelik" },
  { ticker: "BURVA", name: "Burcelik Vana" },
  { ticker: "BVSAN", name: "Bulbuloglu Vinc" },
  { ticker: "BYDNR", name: "Baydoner Restoranlari" },
  { ticker: "CASA", name: "Casa Emtia Petrol" },
  { ticker: "CATES", name: "Cates Elektrik" },
  { ticker: "CELHA", name: "Celik Halat" },
  { ticker: "CEMAS", name: "Cemas Dokum" },
  { ticker: "CEMTS", name: "Cemtas" },
  { ticker: "CEMZY", name: "Cem Zeytin" },
  { ticker: "CEOEM", name: "Ceo Event Medya" },
  { ticker: "CGCAM", name: "Cagdas Cam" },
  { ticker: "CLEBI", name: "Celebi" },
  { ticker: "CMBTN", name: "Cimbeton" },
  { ticker: "CMENT", name: "Cimentas" },
  { ticker: "CONSE", name: "Consus Enerji" },
  { ticker: "COSMO", name: "Cosmos Yat Holding" },
  { ticker: "CRDFA", name: "Creditwest Faktoring" },
  { ticker: "CRFSA", name: "Carrefoursa" },
  { ticker: "CUSAN", name: "Cuhadaroglu Metal" },
  { ticker: "DAGI", name: "Dagi Giyim" },
  { ticker: "DARDL", name: "Dardanel" },
  { ticker: "DCTTR", name: "Dct Trading Dis Ticaret" },
  { ticker: "DENGE", name: "Denge Holding" },
  { ticker: "DERHL", name: "Derluks Yatirim Holding" },
  { ticker: "DERIM", name: "Derimod" },
  { ticker: "DESA", name: "Desa Deri" },
  { ticker: "DESPC", name: "Despec Bilgisayar" },
  { ticker: "DEVA", name: "Deva Holding" },
  { ticker: "DGATE", name: "Datagate Bilgisayar" },
  { ticker: "DGGYO", name: "Dogus GMYO" },
  { ticker: "DGNMO", name: "Doganlar Mobilya" },
  { ticker: "DIRIT", name: "Diriteks Dirilis Tekstil" },
  { ticker: "DITAS", name: "Ditas Bdy" },
  { ticker: "DMLKTG", name: "Emlak Konut Damla Kent Gms" },
  { ticker: "DMRGD", name: "Dmr Unlu Mamuller" },
  { ticker: "DMSAS", name: "Demisas Dokum" },
  { ticker: "DNISI", name: "Dinamik Isi Makina Yalitim" },
  { ticker: "DOCO", name: "Do Co" },
  { ticker: "DOFER", name: "Dofer Yapi Malzemeleri" },
  { ticker: "DOFRB", name: "Dof Robotik" },
  { ticker: "DOGUB", name: "Dogusan" },
  { ticker: "DOKTA", name: "Doktas Dokumculuk" },
  { ticker: "DUNYH", name: "Dunya Holding" },
  { ticker: "DURDO", name: "Duran Dogan Basim" },
  { ticker: "DURKN", name: "Durukan Sekerleme" },
  { ticker: "DYOBY", name: "Dyo Boya" },
  { ticker: "DZGYO", name: "Deniz GMYO" },
  { ticker: "EBEBK", name: "Ebebek Magazacilik" },
  { ticker: "ECOGR", name: "Ecogreen Enerji" },
  { ticker: "ECZYT", name: "Eczacibasi Yatirim" },
  { ticker: "EDATA", name: "E Data Teknoloji" },
  { ticker: "EDIP", name: "Edip Gayrimenkul" },
  { ticker: "EGEEN", name: "Ege Endustri" },
  { ticker: "EGEGY", name: "Egeyapi Avrupa GMYO" },
  { ticker: "EGEPO", name: "Nasmed Egepol" },
  { ticker: "EGGUB", name: "Ege Gubre" },
  { ticker: "EGPRO", name: "Ege Profil" },
  { ticker: "EGSER", name: "Ege Seramik" },
  { ticker: "EKDMR", name: "Ekinciler Demir Celik" },
  { ticker: "EKIM", name: "Ekim Turizm" },
  { ticker: "EKIZ", name: "Ekiz Kimya" },
  { ticker: "EKOS", name: "Ekos Teknoloji" },
  { ticker: "EKSUN", name: "Eksun Gida" },
  { ticker: "ELITE", name: "Elite Naturel Organik Gida" },
  { ticker: "EMKEL", name: "Emek Elektrik" },
  { ticker: "EMNIS", name: "Eminis Ambalaj" },
  { ticker: "EMPAE", name: "Empa Elektronik" },
  { ticker: "ENDAE", name: "Enda Enerji Holding" },
  { ticker: "ENPRA", name: "Enpara Bank" },
  { ticker: "ENSRI", name: "Ensari Sinai Yatirimlar" },
  { ticker: "ENTRA", name: "Ic Enterra Yen Enerji" },
  { ticker: "EPLAS", name: "Egeplast" },
  { ticker: "ERBOS", name: "Erbosan" },
  { ticker: "ERCB", name: "Erciyas Celik Boru" },
  { ticker: "ERSU", name: "Ersu Gida" },
  { ticker: "ESCAR", name: "Escar Filo" },
  { ticker: "ESCOM", name: "Escort Teknoloji" },
  { ticker: "ETILR", name: "Etiler Gida" },
  { ticker: "ETYAT", name: "Euro Trend Yat Ort" },
  { ticker: "EUHOL", name: "Euro Yatirim Holding" },
  { ticker: "EUKYO", name: "Euro Kapital Yat Ort" },
  { ticker: "EUYO", name: "Euro Yat Ort" },
  { ticker: "EYGYO", name: "Eyg GMYO" },
  { ticker: "FADE", name: "Fade Gida" },
  { ticker: "FLAP", name: "Flap Kongre Toplanti Hiz" },
  { ticker: "FMIZP", name: "F M Izmit Piston" },
  { ticker: "FONET", name: "Fonet Bilgi Teknolojileri" },
  { ticker: "FORMT", name: "Formet Metal Ve Cam" },
  { ticker: "FORTE", name: "Forte Bilgi Iletisim" },
  { ticker: "FRIGO", name: "Frigo Pak Gida" },
  { ticker: "FRMPL", name: "Formul Plastik Ve Metal" },
  { ticker: "FZLGY", name: "Fuzul GMYO" },
  { ticker: "GARFA", name: "Garanti Faktoring" },
  { ticker: "GATEG", name: "Gate Group Teknoloji" },
  { ticker: "GEDIK", name: "Gedik Y Men Deg" },
  { ticker: "GEDZA", name: "Gediz Ambalaj" },
  { ticker: "GENKM", name: "Gentas Kimya" },
  { ticker: "GENTS", name: "Gentas" },
  { ticker: "GEREL", name: "Gersan Elektrik" },
  { ticker: "GIPTA", name: "Gipta Ofis Kirtasiye" },
  { ticker: "GLBMD", name: "Global Men Deg" },
  { ticker: "GLCVY", name: "Gelecek Varlik Yonetimi" },
  { ticker: "GLRYH", name: "Guler Yat Holding" },
  { ticker: "GLYHO", name: "Global Yat Holding" },
  { ticker: "GMTAS", name: "Gimat Magazacilik" },
  { ticker: "GOKNR", name: "Goknur Gida" },
  { ticker: "GOLDA", name: "Golda Gida" },
  { ticker: "GOLTS", name: "Goltas Cimento" },
  { ticker: "GOODY", name: "Good Year" },
  { ticker: "GOZDE", name: "Gozde Girisim" },
  { ticker: "GRNYO", name: "Garanti Yat Ort" },
  { ticker: "GSDDE", name: "Gsd Denizcilik" },
  { ticker: "GSDHO", name: "Gsd Holding" },
  { ticker: "GUNDG", name: "Gundogdu Gida" },
  { ticker: "GWIND", name: "Galata Wind Enerji" },
  { ticker: "GZNMI", name: "Gezinomi Seyahat" },
  { ticker: "HATEK", name: "Hatay Tekstil" },
  { ticker: "HATSN", name: "Hatsan Gemi" },
  { ticker: "HDFGS", name: "Hedef Girisim" },
  { ticker: "HEDEF", name: "Hedef Holding" },
  { ticker: "HKTM", name: "Hidropar Hareket Kontrol" },
  { ticker: "HLGYO", name: "Halk GMYO" },
  { ticker: "HOROZ", name: "Horoz Lojistik" },
  { ticker: "HRKET", name: "Hareket Proje Tasimaciligi" },
  { ticker: "HTTBT", name: "Hitit Bilgisayar" },
  { ticker: "HUBVC", name: "Hub Girisim" },
  { ticker: "HUNER", name: "Hun Yenilenebilir Enerji" },
  { ticker: "HURGZ", name: "Hurriyet Gzt" },
  { ticker: "ICBCT", name: "Icbc Turkey Bank" },
  { ticker: "ICUGS", name: "Icu Girisim" },
  { ticker: "IDGYO", name: "Idealist GMYO" },
  { ticker: "IHAAS", name: "Ihlas Haber Ajansi" },
  { ticker: "IHEVA", name: "Ihlas Ev Aletleri" },
  { ticker: "IHGZT", name: "Ihlas Gazetecilik" },
  { ticker: "IHLAS", name: "Ihlas Holding" },
  { ticker: "IHLGM", name: "Ihlas Gayrimenkul" },
  { ticker: "IHYAY", name: "Ihlas Yayin Holding" },
  { ticker: "IMASM", name: "Imas Makina" },
  { ticker: "INDES", name: "Indeks Bilgisayar" },
  { ticker: "INFO", name: "Info Yatirim" },
  { ticker: "INGRM", name: "Ingram Bilisim" },
  { ticker: "INTEK", name: "Innosa Teknoloji" },
  { ticker: "INTEM", name: "Intema" },
  { ticker: "INVEO", name: "Inveo Yatirim Holding" },
  { ticker: "INVES", name: "Investco Holding" },
  { ticker: "ISATR", name: "Is Bankasi A" },
  { ticker: "ISBIR", name: "Isbir Holding" },
  { ticker: "ISBTR", name: "Is Bankasi B" },
  { ticker: "ISDMR", name: "Iskenderun Demir Celik" },
  { ticker: "ISFIN", name: "Is Finkir" },
  { ticker: "ISGSY", name: "Is Girisim" },
  { ticker: "ISGYO", name: "Is GMYO" },
  { ticker: "ISKPL", name: "Isik Plastik" },
  { ticker: "ISKUR", name: "Is Bankasi Kur" },
  { ticker: "ISSEN", name: "Isbir Sentetik Dokuma" },
  { ticker: "ISVEA", name: "Isvea Seramik Ve Banyo" },
  { ticker: "ISYAT", name: "Is Yat Ort" },
  { ticker: "IZFAS", name: "Izmir Firca" },
  { ticker: "IZINV", name: "Iz Yatirim Holding" },
  { ticker: "IZMDC", name: "Izmir Demir Celik" },
  { ticker: "JANTS", name: "Jantsa Jant Sanayi" },
  { ticker: "KAPLM", name: "Kaplamin" },
  { ticker: "KAREL", name: "Karel Elektronik" },
  { ticker: "KARSN", name: "Karsan Otomotiv" },
  { ticker: "KARTN", name: "Kartonsan" },
  { ticker: "KATMR", name: "Katmerciler Ekipman" },
  { ticker: "KAYSE", name: "Kayseri Seker Fabrikasi" },
  { ticker: "KBORU", name: "Kuzey Boru" },
  { ticker: "KCAER", name: "Kocaer Celik" },
  { ticker: "KENT", name: "Kent Gida" },
  { ticker: "KERVN", name: "Kervansaray Yat Holding" },
  { ticker: "KFEIN", name: "Kafein Yazilim" },
  { ticker: "KGYO", name: "Koray GMYO" },
  { ticker: "KIMMR", name: "Kim Market Ersan Alisveris" },
  { ticker: "KLGYO", name: "Kiler GMYO" },
  { ticker: "KLKIM", name: "Kalekim Kimyevi Maddeler" },
  { ticker: "KLMSN", name: "Klimasan Klima" },
  { ticker: "KLNMA", name: "T Kalkinma Bank" },
  { ticker: "KLSER", name: "Kaleseramik" },
  { ticker: "KLSYN", name: "Koleksiyon Mobilya" },
  { ticker: "KLYPV", name: "Kalyon Gunes Teknolojileri" },
  { ticker: "KMPUR", name: "Kimteks Poliuretan" },
  { ticker: "KNFRT", name: "Konfrut Tarim" },
  { ticker: "KOCMT", name: "Koc Metalurji" },
  { ticker: "KONKA", name: "Konya Kagit" },
  { ticker: "KONTR", name: "Kontrolmatik Teknoloji" },
  { ticker: "KONYA", name: "Konya Cimento" },
  { ticker: "KOPOL", name: "Koza Polyester" },
  { ticker: "KORDS", name: "Kordsa Teknik Tekstil" },
  { ticker: "KOTON", name: "Koton Magazacilik" },
  { ticker: "KRDMA", name: "Kardemir A" },
  { ticker: "KRDMB", name: "Kardemir B" },
  { ticker: "KRGYO", name: "Korfez GMYO" },
  { ticker: "KRONT", name: "Kron Teknoloji" },
  { ticker: "KRPLS", name: "Koroplast Temizlik Ambalaj" },
  { ticker: "KRSTL", name: "Kristal Kola" },
  { ticker: "KRTEK", name: "Karsu Tekstil" },
  { ticker: "KRVGD", name: "Kervan Gida" },
  { ticker: "KSTUR", name: "Kustur Kusadasi Turizm" },
  { ticker: "KTSKR", name: "Kutahya Seker Fabrikasi" },
  { ticker: "KUTPO", name: "Kutahya Porselen" },
  { ticker: "KUVVA", name: "Kuvva Gida" },
  { ticker: "KZBGY", name: "Kizilbuk GYO" },
  { ticker: "KZGYO", name: "Kuzugrup GMYO" },
  { ticker: "LIDER", name: "Ldr Turizm" },
  { ticker: "LIDFA", name: "Lider Faktoring" },
  { ticker: "LILAK", name: "Lila Kagit" },
  { ticker: "LINK", name: "Link Bilgisayar" },
  { ticker: "LKMNH", name: "Lokman Hekim Saglik" },
  { ticker: "LMKDC", name: "Limak Dogu Anadolu" },
  { ticker: "LOGO", name: "Logo Yazilim" },
  { ticker: "LRSHO", name: "Loras Holding" },
  { ticker: "LUKSK", name: "Luks Kadife" },
  { ticker: "LXGYO", name: "Luxera GMYO" },
  { ticker: "LYDHO", name: "Lydia Holding" },
  { ticker: "LYDYE", name: "Lydia Yesil Enerji" },
  { ticker: "MAALT", name: "Marmaris Altinyunus" },
  { ticker: "MACKO", name: "Mackolik Internet Hizmetleri" },
  { ticker: "MAKIM", name: "Makim Makine" },
  { ticker: "MAKTK", name: "Makina Takim" },
  { ticker: "MANAS", name: "Manas Enerji Yonetimi" },
  { ticker: "MARBL", name: "Tureks Turunc Madencilik" },
  { ticker: "MARKA", name: "Marka Yatirim Holding" },
  { ticker: "MARMR", name: "Marmara Holding" },
  { ticker: "MARTI", name: "Marti Otel" },
  { ticker: "MCARD", name: "Metropal Kurumsal Hizmetler" },
  { ticker: "MEDTR", name: "Meditera Tibbi Malzeme" },
  { ticker: "MEGAP", name: "Mega Polietilen" },
  { ticker: "MEGMT", name: "Mega Metal" },
  { ticker: "MEKAG", name: "Meka Global Makine" },
  { ticker: "MEPET", name: "Metro Petrol Ve Tesisleri" },
  { ticker: "MERCN", name: "Mercan Kimya" },
  { ticker: "MERIT", name: "Merit Turizm" },
  { ticker: "MERKO", name: "Merko Gida" },
  { ticker: "METRO", name: "Metro Holding" },
  { ticker: "MEYSU", name: "Meysu Gida" },
  { ticker: "MHRGY", name: "Mhr GMYO" },
  { ticker: "MMCAS", name: "Mmc San Ve Tic Yat" },
  { ticker: "MNDRS", name: "Menderes Tekstil" },
  { ticker: "MNDTR", name: "Mondi Turkey" },
  { ticker: "MOBTL", name: "Mobiltel Iletisim" },
  { ticker: "MOGAN", name: "Mogan Enerji" },
  { ticker: "MOPAS", name: "Mopas Marketcilik" },
  { ticker: "MRGYO", name: "Marti GMYO" },
  { ticker: "MRSHL", name: "Marshall" },
  { ticker: "MSGYO", name: "Mistral GMYO" },
  { ticker: "MTRKS", name: "Matriks Finansal Teknolojiler" },
  { ticker: "MTRYO", name: "Metro Yat Ort" },
  { ticker: "MZHLD", name: "Mazhar Zorlu Holding" },
  { ticker: "NATEN", name: "Naturel Enerji" },
  { ticker: "NETAS", name: "Netas Telekom" },
  { ticker: "NETCD", name: "Netcad Yazilim" },
  { ticker: "NIBAS", name: "Nigbas Nigde Beton" },
  { ticker: "NTGAZ", name: "Naturelgaz" },
  { ticker: "NTHOL", name: "Net Holding" },
  { ticker: "NUGYO", name: "Nurol GMYO" },
  { ticker: "NUHCM", name: "Nuh Cimento" },
  { ticker: "OBASE", name: "Obase Bilgisayar" },
  { ticker: "OFSYM", name: "Ofis Yem Gida" },
  { ticker: "ONCSM", name: "Oncosem Onkolojik Sistemler" },
  { ticker: "ONRYT", name: "Onur Teknoloji" },
  { ticker: "ORCAY", name: "Orcay Ortakoy Cay Sanayi" },
  { ticker: "ORGE", name: "Orge Enerji Elektrik" },
  { ticker: "ORMA", name: "Orma Orman Mahsulleri" },
  { ticker: "ORZAX", name: "Orzaks Ilac" },
  { ticker: "OSMEN", name: "Osmanli Menkul" },
  { ticker: "OSTIM", name: "Ostim Endustriyel Yat" },
  { ticker: "OTTO", name: "Otto Holding" },
  { ticker: "OYAYO", name: "Oyak Yat Ort" },
  { ticker: "OYLUM", name: "Oylum Sinai Yatirimlar" },
  { ticker: "OYYAT", name: "Oyak Yatirim Menkul" },
  { ticker: "OZATD", name: "Ozata Denizcilik" },
  { ticker: "OZGYO", name: "Ozderici GMYO" },
  { ticker: "OZKGY", name: "Ozak GMYO" },
  { ticker: "OZRDN", name: "Ozerden Ambalaj" },
  { ticker: "OZSUB", name: "Ozsu Balik" },
  { ticker: "OZYSR", name: "Ozyasar Tel" },
  { ticker: "PAGYO", name: "Panora GMYO" },
  { ticker: "PAMEL", name: "Pamel Elektrik" },
  { ticker: "PAPIL", name: "Papilon Savunma" },
  { ticker: "PARSN", name: "Parsan" },
  { ticker: "PCILT", name: "Pc Iletisim Medya" },
  { ticker: "PEKGY", name: "Peker GMYO" },
  { ticker: "PENGD", name: "Penguen Gida" },
  { ticker: "PENTA", name: "Penta Teknoloji Urunleri Dagitim" },
  { ticker: "PETUN", name: "Pinar Et Ve Un" },
  { ticker: "PINSU", name: "Pinar Su" },
  { ticker: "PKART", name: "Plastikkart" },
  { ticker: "PKENT", name: "Petrokent Turizm" },
  { ticker: "PLTUR", name: "Platform Turizm" },
  { ticker: "PNLSN", name: "Panelsan Cati Cephe" },
  { ticker: "PNSUT", name: "Pinar Sut" },
  { ticker: "POLHO", name: "Polisan Holding" },
  { ticker: "POLTK", name: "Politeknik Metal" },
  { ticker: "PRDGS", name: "Pardus Girisim" },
  { ticker: "PRKAB", name: "Turk Prysmian Kablo" },
  { ticker: "PRKME", name: "Park Elekmadencilik" },
  { ticker: "PRZMA", name: "Prizma Press Matbaacilik" },
  { ticker: "PSDTC", name: "Pergamon Dis Ticaret" },
  { ticker: "QNBFK", name: "Qnb Finansal Kiralama" },
  { ticker: "QNBTR", name: "Qnb Bank" },
  { ticker: "RAYSG", name: "Ray Sigorta" },
  { ticker: "RGYAS", name: "Ronesans Gayrimenkul Yat" },
  { ticker: "RNPOL", name: "Rainbow Polikarbonat" },
  { ticker: "RODRG", name: "Rodrigo Tekstil" },
  { ticker: "RTALB", name: "Rta Laboratuvarlari" },
  { ticker: "RUBNS", name: "Rubenis Tekstil" },
  { ticker: "RUZYE", name: "Ruzy Madencilik Ve Enerji" },
  { ticker: "RYGYO", name: "Reysas GMYO" },
  { ticker: "RYSAS", name: "Reysas Lojistik" },
  { ticker: "SAFKR", name: "Safkar Ege Sogutmacilik" },
  { ticker: "SAMAT", name: "Saray Matbaacilik" },
  { ticker: "SANEL", name: "Sanel Muhendislik" },
  { ticker: "SANFM", name: "Sanifoam Endustri" },
  { ticker: "SANKO", name: "Sanko Pazarlama" },
  { ticker: "SARAE", name: "Sa Ra Enerji" },
  { ticker: "SAYAS", name: "Say Yenilenebilir Enerji" },
  { ticker: "SDTTR", name: "Sdt Uzay Ve Savunma" },
  { ticker: "SEGMN", name: "Segmen Kardesler Gida" },
  { ticker: "SEGYO", name: "Seker GMYO" },
  { ticker: "SEKFK", name: "Seker Fin Kir" },
  { ticker: "SEKFKR", name: "Seker Fin Kir Rhkp" },
  { ticker: "SEKUR", name: "Sekuro Plastik" },
  { ticker: "SELEC", name: "Selcuk Ecza Deposu" },
  { ticker: "SELVA", name: "Selva Gida" },
  { ticker: "SERNT", name: "Seranit Granit Seramik" },
  { ticker: "SEYKM", name: "Seyitler Kimya" },
  { ticker: "SILVR", name: "Silverline Endustri" },
  { ticker: "SKTAS", name: "Soktas" },
  { ticker: "SKYLP", name: "Skyalp Finansal Teknolojiler" },
  { ticker: "SKYMD", name: "Seker Yatirim" },
  { ticker: "SMART", name: "Smartiks Yazilim" },
  { ticker: "SMRTG", name: "Smart Gunes Enerjisi Tek" },
  { ticker: "SMRVA", name: "Sumer Varlik Yonetim" },
  { ticker: "SNGYO", name: "Sinpas GMYO" },
  { ticker: "SNICA", name: "Sanica Isi Sanayi" },
  { ticker: "SNPAM", name: "Sonmez Pamuklu" },
  { ticker: "SODSN", name: "Sodas Sodyum Sanayii" },
  { ticker: "SOHOE", name: "Soho Giyim Ve Enerji" },
  { ticker: "SOKE", name: "Soke Degirmencilik" },
  { ticker: "SONME", name: "Sonmez Filament" },
  { ticker: "SRVGY", name: "Servet GMYO" },
  { ticker: "SSAAT", name: "Saat Ve Saat Sanayi" },
  { ticker: "SUMAS", name: "Sumas Suni Tahta" },
  { ticker: "SUNTK", name: "Sun Tekstil" },
  { ticker: "SURGY", name: "Sur Tatil Evleri GMYO" },
  { ticker: "SUWEN", name: "Suwen Tekstil" },
  { ticker: "SVGYO", name: "Savur GMYO" },
  { ticker: "TABGD", name: "Tab Gida" },
  { ticker: "TARKM", name: "Tarkim Bitki Koruma" },
  { ticker: "TATEN", name: "Tatlipinar Enerji Uretim" },
  { ticker: "TATGD", name: "Tat Gida" },
  { ticker: "TBORG", name: "Ttuborg" },
  { ticker: "TCKRC", name: "Kirac Galvaniz" },
  { ticker: "TDGYO", name: "Trend GMYO" },
  { ticker: "TEHOL", name: "Tera Yatirim Tek Hol" },
  { ticker: "TEKTU", name: "Tek Art Turizm" },
  { ticker: "TERA", name: "Tera Yatirim Menkul Degerler" },
  { ticker: "TEZOL", name: "Europap Tezol Kagit" },
  { ticker: "TGSAS", name: "Tgs Dis Ticaret" },
  { ticker: "TKNSA", name: "Teknosa Ic Ve Dis Ticaret" },
  { ticker: "TLMAN", name: "Trabzon Liman" },
  { ticker: "TMPOL", name: "Temapol Polimer Plastik" },
  { ticker: "TMSN", name: "Tumosan Motor Ve Traktor" },
  { ticker: "TNZTP", name: "Tapdi Tinaztepe" },
  { ticker: "TRCAS", name: "Turcas Holding" },
  { ticker: "TRGYO", name: "Torunlar GMYO" },
  { ticker: "TRHOL", name: "Tera Finansal Yat Hol" },
  { ticker: "TRILC", name: "Turk Ilac Serum" },
  { ticker: "TSGYO", name: "Tskb GMYO" },
  { ticker: "TSPOR", name: "Trabzonspor Sportif" },
  { ticker: "TTRAK", name: "Turk Traktor" },
  { ticker: "TUCLK", name: "Tugcelik" },
  { ticker: "TUREX", name: "Tureks Turizm Tasimacilik" },
  { ticker: "TURGG", name: "Turker Proje Gayrimenkul" },
  { ticker: "UCAYM", name: "Ucay Muhendislik" },
  { ticker: "UFUK", name: "Ufuk Yatirim" },
  { ticker: "ULAS", name: "Ulaslar Turizm Yat" },
  { ticker: "ULUFA", name: "Ulusal Faktoring" },
  { ticker: "ULUSE", name: "Ulusoy Elektrik" },
  { ticker: "ULUUN", name: "Ulusoy Un Sanayi" },
  { ticker: "UMPAS", name: "Umpas Holding" },
  { ticker: "UNLU", name: "Unlu Yatirim Holding" },
  { ticker: "USAK", name: "Usak Seramik" },
  { ticker: "VAKFA", name: "Vakif Faktoring" },
  { ticker: "VAKFN", name: "Vakif Fin Kir" },
  { ticker: "VAKKO", name: "Vakko Tekstil" },
  { ticker: "VANGD", name: "Vanet Gida" },
  { ticker: "VBTYZ", name: "Vbt Yazilim" },
  { ticker: "VERTU", name: "Verusaturk Girisim" },
  { ticker: "VERUS", name: "Verusa Holding" },
  { ticker: "VESBE", name: "Vestel Beyaz Esya" },
  { ticker: "VKFYO", name: "Vakif Yat Ort" },
  { ticker: "VKGYO", name: "Vakif GMYO" },
  { ticker: "VKING", name: "Viking Kagit" },
  { ticker: "VRGYO", name: "Vera Konsept GMYO" },
  { ticker: "VSNMD", name: "Visne Madencilik" },
  { ticker: "YAPRK", name: "Yaprak Sut Ve Besi Cift" },
  { ticker: "YATAS", name: "Yatas" },
  { ticker: "YAYLA", name: "Yayla En Ur Tur Ve Ins" },
  { ticker: "YBTAS", name: "Yibitas Insaat Malzeme" },
  { ticker: "YEOTK", name: "Yeo Teknoloji Enerji" },
  { ticker: "YESIL", name: "Yesil Yatirim Holding" },
  { ticker: "YGGYO", name: "Yeni Gimat GMYO" },
  { ticker: "YIGIT", name: "Yigit Aku" },
  { ticker: "YKSLN", name: "Yukselen Celik" },
  { ticker: "YONGA", name: "Yonga Mobilya" },
  { ticker: "YUNSA", name: "Yunsa" },
  { ticker: "YYAPI", name: "Yesil Yapi" },
  { ticker: "YYLGD", name: "Yayla Gida" },
  { ticker: "ZEDUR", name: "Zedur Enerji" },
  { ticker: "ZERGY", name: "Zeray GMYO" },
  { ticker: "ZGYO", name: "Z GMYO" },
  { ticker: "ZRGYO", name: "Ziraat GMYO" },
];
