// ABD büyük şirketler evreni: NASDAQ-100 (NDX) ∪ S&P 100 (SPX, "OEX") birleşimi.
// BIST_STOCKS'taki gibi statik, elle bakımlı bir liste — endeks kompozisyonu
// çeyreklik/yıllık gözden geçiriliyor, üyelik değiştikçe burayı güncelleyin.
// `indices`: hissenin hangi endeks(ler)de olduğu (['NDX'], ['SPX'] veya ikisi
// birden) — frontend'de sekme içi filtre olarak kullanılır.
// `symbol`: Yahoo Finance sembolü ticker'dan farklıysa (ör. BRK.B -> BRK-B).
// Fiyatlar USD; BIST'in aksine ₺'ye çevrilmez (ABD hissesi ABD doları ile
// karşılaştırılır).
export const US_STOCKS = [
  // --- Teknoloji: Dev platformlar / yazılım -----------------------------
  { ticker: 'AAPL',  name: 'Apple',                    sector: 'Teknoloji',        indices: ['NDX', 'SPX'] },
  { ticker: 'MSFT',  name: 'Microsoft',                sector: 'Yazılım',          indices: ['NDX', 'SPX'] },
  { ticker: 'GOOGL', name: 'Alphabet (A)',              sector: 'Teknoloji',        indices: ['NDX', 'SPX'] },
  { ticker: 'GOOG',  name: 'Alphabet (C)',              sector: 'Teknoloji',        indices: ['NDX', 'SPX'] },
  { ticker: 'AMZN',  name: 'Amazon',                    sector: 'Perakende/Bulut',  indices: ['NDX', 'SPX'] },
  { ticker: 'META',  name: 'Meta Platforms',            sector: 'Teknoloji',        indices: ['NDX', 'SPX'] },
  { ticker: 'NVDA',  name: 'NVIDIA',                    sector: 'Yarı İletken',     indices: ['NDX', 'SPX'] },
  { ticker: 'AVGO',  name: 'Broadcom',                  sector: 'Yarı İletken',     indices: ['NDX', 'SPX'] },
  { ticker: 'ORCL',  name: 'Oracle',                    sector: 'Yazılım',          indices: ['SPX'] },
  { ticker: 'ADBE',  name: 'Adobe',                     sector: 'Yazılım',          indices: ['NDX'] },
  { ticker: 'CRM',   name: 'Salesforce',                sector: 'Yazılım',          indices: ['SPX'] },
  { ticker: 'NFLX',  name: 'Netflix',                   sector: 'Medya/Yayın',      indices: ['NDX'] },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',    sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'INTC',  name: 'Intel',                     sector: 'Yarı İletken',     indices: ['SPX'] },
  { ticker: 'CSCO',  name: 'Cisco Systems',              sector: 'Ağ Donanımı',      indices: ['NDX'] },
  { ticker: 'ACN',   name: 'Accenture',                 sector: 'BT Danışmanlık',   indices: ['SPX'] },
  { ticker: 'IBM',   name: 'IBM',                       sector: 'BT Hizmetleri',    indices: ['SPX'] },
  { ticker: 'NOW',   name: 'ServiceNow',                sector: 'Yazılım',          indices: ['NDX', 'SPX'] },
  { ticker: 'QCOM',  name: 'Qualcomm',                  sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'TXN',   name: 'Texas Instruments',         sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'AMAT',  name: 'Applied Materials',         sector: 'Yarı İletken Ekip.', indices: ['NDX'] },
  { ticker: 'LRCX',  name: 'Lam Research',              sector: 'Yarı İletken Ekip.', indices: ['NDX'] },
  { ticker: 'KLAC',  name: 'KLA Corp',                  sector: 'Yarı İletken Ekip.', indices: ['NDX'] },
  { ticker: 'ADI',   name: 'Analog Devices',            sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'MU',    name: 'Micron Technology',         sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'NXPI',  name: 'NXP Semiconductors',        sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'ON',    name: 'ON Semiconductor',          sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'ASML',  name: 'ASML Holding',              sector: 'Yarı İletken Ekip.', indices: ['NDX'] },
  { ticker: 'GFS',   name: 'GlobalFoundries',           sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'ARM',   name: 'Arm Holdings',              sector: 'Yarı İletken/IP',  indices: ['NDX'] },
  { ticker: 'MRVL',  name: 'Marvell Technology',        sector: 'Yarı İletken',     indices: ['NDX'] },
  { ticker: 'CDNS',  name: 'Cadence Design Systems',    sector: 'Tasarım Yazılımı', indices: ['NDX'] },
  { ticker: 'SNPS',  name: 'Synopsys',                  sector: 'Tasarım Yazılımı', indices: ['NDX'] },
  { ticker: 'ANSS',  name: 'Ansys',                     sector: 'Mühendislik Yazılımı', indices: ['NDX'] },
  { ticker: 'INTU',  name: 'Intuit',                    sector: 'Yazılım',          indices: ['NDX'] },
  { ticker: 'ADP',   name: 'Automatic Data Processing', sector: 'İş Hizmetleri',    indices: ['NDX'] },
  { ticker: 'PAYX',  name: 'Paychex',                   sector: 'İş Hizmetleri',    indices: ['NDX'] },
  { ticker: 'PANW',  name: 'Palo Alto Networks',        sector: 'Siber Güvenlik',   indices: ['NDX'] },
  { ticker: 'CRWD',  name: 'CrowdStrike',               sector: 'Siber Güvenlik',   indices: ['NDX'] },
  { ticker: 'FTNT',  name: 'Fortinet',                  sector: 'Siber Güvenlik',   indices: ['NDX'] },
  { ticker: 'ZS',    name: 'Zscaler',                   sector: 'Siber Güvenlik',   indices: ['NDX'] },
  { ticker: 'DDOG',  name: 'Datadog',                   sector: 'Bulut Yazılım',    indices: ['NDX'] },
  { ticker: 'TEAM',  name: 'Atlassian',                 sector: 'Yazılım',          indices: ['NDX'] },
  { ticker: 'WDAY',  name: 'Workday',                   sector: 'Yazılım',          indices: ['NDX'] },
  { ticker: 'CDW',   name: 'CDW Corp',                  sector: 'BT Dağıtım',       indices: ['NDX'] },
  { ticker: 'MELI',  name: 'MercadoLibre',              sector: 'E-ticaret',        indices: ['NDX'] },
  { ticker: 'PDD',   name: 'PDD Holdings',              sector: 'E-ticaret',        indices: ['NDX'] },
  { ticker: 'ABNB',  name: 'Airbnb',                    sector: 'Seyahat/Platform', indices: ['NDX'] },
  { ticker: 'DASH',  name: 'DoorDash',                  sector: 'Platform/Teslimat', indices: ['NDX'] },
  { ticker: 'BKNG',  name: 'Booking Holdings',          sector: 'Seyahat/Platform', indices: ['NDX'] },
  { ticker: 'TTD',   name: 'The Trade Desk',            sector: 'AdTech',           indices: ['NDX'] },
  { ticker: 'APP',   name: 'AppLovin',                  sector: 'AdTech/Mobil',     indices: ['NDX'] },
  { ticker: 'AXON',  name: 'Axon Enterprise',           sector: 'Kamu Güvenliği Tekn.', indices: ['NDX'] },
  { ticker: 'CEG',   name: 'Constellation Energy',      sector: 'Enerji Üretimi',   indices: ['NDX'] },
  { ticker: 'TMUS',  name: 'T-Mobile US',               sector: 'Telekom',          indices: ['NDX'] },
  { ticker: 'CMCSA', name: 'Comcast',                   sector: 'Medya/Telekom',    indices: ['NDX', 'SPX'] },
  { ticker: 'CHTR',  name: 'Charter Communications',    sector: 'Kablo/Telekom',    indices: ['NDX'] },
  { ticker: 'WBD',   name: 'Warner Bros Discovery',     sector: 'Medya',            indices: ['NDX'] },
  { ticker: 'SIRI',  name: 'Sirius XM',                 sector: 'Medya',            indices: ['NDX'] },
  { ticker: 'MAR',   name: 'Marriott International',    sector: 'Otelcilik',        indices: ['NDX'] },
  { ticker: 'ORLY',  name: "O'Reilly Automotive",       sector: 'Perakende (Oto Yedek Parça)', indices: ['NDX'] },
  { ticker: 'ROST',  name: 'Ross Stores',                sector: 'Perakende',        indices: ['NDX'] },
  { ticker: 'LULU',  name: 'Lululemon Athletica',       sector: 'Perakende (Giyim)', indices: ['NDX'] },
  { ticker: 'CTAS',  name: 'Cintas',                    sector: 'İş Hizmetleri',    indices: ['NDX'] },
  { ticker: 'FAST',  name: 'Fastenal',                  sector: 'Sanayi Dağıtım',   indices: ['NDX'] },
  { ticker: 'ODFL',  name: 'Old Dominion Freight Line', sector: 'Lojistik',         indices: ['NDX'] },
  { ticker: 'CSX',   name: 'CSX Corp',                  sector: 'Demiryolu',        indices: ['NDX'] },
  { ticker: 'PCAR',  name: 'Paccar',                    sector: 'Ağır Ticari Araç', indices: ['NDX'] },
  { ticker: 'HON',   name: 'Honeywell',                 sector: 'Sanayi/Havacılık', indices: ['NDX', 'SPX'] },
  { ticker: 'ROP',   name: 'Roper Technologies',        sector: 'Sanayi/Yazılım',   indices: ['NDX'] },
  { ticker: 'VRSK',  name: 'Verisk Analytics',          sector: 'Veri/Analitik',    indices: ['NDX'] },
  { ticker: 'CSGP',  name: 'CoStar Group',              sector: 'Emlak Verisi',     indices: ['NDX'] },
  { ticker: 'GEN',   name: 'Gen Digital',               sector: 'Siber Güvenlik',   indices: ['NDX'] },
  { ticker: 'MSTR',  name: 'Strategy (MicroStrategy)',  sector: 'Yazılım/Bitcoin Hazinesi', indices: ['NDX'] },

  // --- Sağlık / İlaç ------------------------------------------------------
  { ticker: 'LLY',   name: 'Eli Lilly',                 sector: 'İlaç',             indices: ['SPX'] },
  { ticker: 'UNH',   name: 'UnitedHealth Group',        sector: 'Sağlık Sigortası', indices: ['SPX'] },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',         sector: 'İlaç/Sağlık',      indices: ['SPX'] },
  { ticker: 'ABBV',  name: 'AbbVie',                    sector: 'İlaç',             indices: ['SPX'] },
  { ticker: 'MRK',   name: 'Merck & Co',                sector: 'İlaç',             indices: ['SPX'] },
  { ticker: 'PFE',   name: 'Pfizer',                    sector: 'İlaç',             indices: ['SPX'] },
  { ticker: 'ABT',   name: 'Abbott Laboratories',       sector: 'Tıbbi Cihaz/Sağlık', indices: ['SPX'] },
  { ticker: 'TMO',   name: 'Thermo Fisher Scientific',  sector: 'Yaşam Bilimleri',  indices: ['SPX'] },
  { ticker: 'DHR',   name: 'Danaher',                   sector: 'Yaşam Bilimleri',  indices: ['SPX'] },
  { ticker: 'AMGN',  name: 'Amgen',                     sector: 'Biyoteknoloji',    indices: ['NDX', 'SPX'] },
  { ticker: 'GILD',  name: 'Gilead Sciences',           sector: 'Biyoteknoloji',    indices: ['NDX'] },
  { ticker: 'VRTX',  name: 'Vertex Pharmaceuticals',    sector: 'Biyoteknoloji',    indices: ['NDX'] },
  { ticker: 'REGN',  name: 'Regeneron Pharmaceuticals', sector: 'Biyoteknoloji',    indices: ['NDX'] },
  { ticker: 'BIIB',  name: 'Biogen',                    sector: 'Biyoteknoloji',    indices: ['NDX'] },
  { ticker: 'ILMN',  name: 'Illumina',                  sector: 'Yaşam Bilimleri',  indices: ['NDX'] },
  { ticker: 'ISRG',  name: 'Intuitive Surgical',        sector: 'Tıbbi Cihaz',      indices: ['NDX'] },
  { ticker: 'DXCM',  name: 'Dexcom',                    sector: 'Tıbbi Cihaz',      indices: ['NDX'] },
  { ticker: 'IDXX',  name: 'IDEXX Laboratories',        sector: 'Veteriner/Tanı',   indices: ['NDX'] },
  { ticker: 'ALGN',  name: 'Align Technology',          sector: 'Tıbbi Cihaz',      indices: ['NDX'] },
  { ticker: 'GEHC',  name: 'GE HealthCare',             sector: 'Tıbbi Görüntüleme', indices: ['NDX'] },
  { ticker: 'SYK',   name: 'Stryker',                   sector: 'Tıbbi Cihaz',      indices: ['SPX'] },
  { ticker: 'MDT',   name: 'Medtronic',                 sector: 'Tıbbi Cihaz',      indices: ['SPX'] },
  { ticker: 'BSX',   name: 'Boston Scientific',         sector: 'Tıbbi Cihaz',      indices: ['SPX'] },
  { ticker: 'EW',    name: 'Edwards Lifesciences',      sector: 'Tıbbi Cihaz',      indices: ['SPX'] },
  { ticker: 'ELV',   name: 'Elevance Health',           sector: 'Sağlık Sigortası', indices: ['SPX'] },
  { ticker: 'CI',    name: 'The Cigna Group',           sector: 'Sağlık Sigortası', indices: ['SPX'] },
  { ticker: 'ZTS',   name: 'Zoetis',                    sector: 'Veteriner İlaç',   indices: ['SPX'] },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',      sector: 'İlaç',             indices: ['SPX'] },

  // --- Finans -------------------------------------------------------------
  { ticker: 'JPM',   name: 'JPMorgan Chase',            sector: 'Bankacılık',       indices: ['SPX'] },
  { ticker: 'V',     name: 'Visa',                      sector: 'Ödeme Sistemleri', indices: ['SPX'] },
  { ticker: 'MA',    name: 'Mastercard',                sector: 'Ödeme Sistemleri', indices: ['SPX'] },
  { ticker: 'BAC',   name: 'Bank of America',           sector: 'Bankacılık',       indices: ['SPX'] },
  { ticker: 'WFC',   name: 'Wells Fargo',               sector: 'Bankacılık',       indices: ['SPX'] },
  { ticker: 'GS',    name: 'Goldman Sachs',             sector: 'Yatırım Bankacılığı', indices: ['SPX'] },
  { ticker: 'MS',    name: 'Morgan Stanley',            sector: 'Yatırım Bankacılığı', indices: ['SPX'] },
  { ticker: 'C',     name: 'Citigroup',                 sector: 'Bankacılık',       indices: ['SPX'] },
  { ticker: 'SCHW',  name: 'Charles Schwab',            sector: 'Aracı Kurum',      indices: ['SPX'] },
  { ticker: 'USB',   name: 'U.S. Bancorp',              sector: 'Bankacılık',       indices: ['SPX'] },
  { ticker: 'BLK',   name: 'BlackRock',                 sector: 'Varlık Yönetimi',  indices: ['SPX'] },
  { ticker: 'SPGI',  name: 'S&P Global',                sector: 'Finansal Veri',    indices: ['SPX'] },
  { ticker: 'MMC',   name: 'Marsh McLennan',            sector: 'Sigorta Brokerliği', indices: ['SPX'] },
  { ticker: 'CB',    name: 'Chubb',                     sector: 'Sigorta',          indices: ['SPX'] },
  { ticker: 'PGR',   name: 'Progressive',                sector: 'Sigorta',          indices: ['SPX'] },
  { ticker: 'AXP',   name: 'American Express',          sector: 'Ödeme/Kredi Kartı', indices: ['SPX'] },
  { ticker: 'PYPL',  name: 'PayPal',                    sector: 'Dijital Ödeme',    indices: ['NDX'] },

  // --- Tüketim / Perakende / Gıda ------------------------------------------
  { ticker: 'WMT',   name: 'Walmart',                   sector: 'Perakende',        indices: ['SPX'] },
  { ticker: 'COST',  name: 'Costco Wholesale',          sector: 'Perakende (Toptan)', indices: ['NDX', 'SPX'] },
  { ticker: 'HD',    name: 'Home Depot',                sector: 'Perakende (Yapı Market)', indices: ['SPX'] },
  { ticker: 'LOW',   name: "Lowe's",                    sector: 'Perakende (Yapı Market)', indices: ['SPX'] },
  { ticker: 'TGT',   name: 'Target',                    sector: 'Perakende',        indices: ['SPX'] },
  { ticker: 'TJX',   name: 'TJX Companies',              sector: 'Perakende (İndirim)', indices: ['SPX'] },
  { ticker: 'PG',    name: 'Procter & Gamble',          sector: 'Tüketim Ürünleri', indices: ['SPX'] },
  { ticker: 'KO',    name: 'Coca-Cola',                 sector: 'İçecek',           indices: ['SPX'] },
  { ticker: 'PEP',   name: 'PepsiCo',                   sector: 'Gıda/İçecek',      indices: ['NDX', 'SPX'] },
  { ticker: 'CCEP',  name: 'Coca-Cola Europacific Partners', sector: 'İçecek Şişeleme', indices: ['NDX'] },
  { ticker: 'MDLZ',  name: 'Mondelez International',    sector: 'Gıda',             indices: ['NDX'] },
  { ticker: 'KHC',   name: 'Kraft Heinz',               sector: 'Gıda',             indices: ['NDX'] },
  { ticker: 'KDP',   name: 'Keurig Dr Pepper',          sector: 'İçecek',           indices: ['NDX'] },
  { ticker: 'MNST',  name: 'Monster Beverage',          sector: 'İçecek',           indices: ['NDX'] },
  { ticker: 'MO',    name: 'Altria Group',              sector: 'Tütün',            indices: ['SPX'] },
  { ticker: 'PM',    name: 'Philip Morris International', sector: 'Tütün',          indices: ['SPX'] },
  { ticker: 'MCD',   name: "McDonald's",                sector: 'Restoran',         indices: ['SPX'] },
  { ticker: 'SBUX',  name: 'Starbucks',                 sector: 'Restoran/Kafe',    indices: ['NDX'] },
  { ticker: 'NKE',   name: 'Nike',                      sector: 'Giyim/Spor',       indices: ['SPX'] },
  { ticker: 'DIS',   name: 'The Walt Disney Company',   sector: 'Medya/Eğlence',    indices: ['SPX'] },
  { ticker: 'EA',    name: 'Electronic Arts',            sector: 'Oyun',             indices: ['NDX'] },
  { ticker: 'TTWO',  name: 'Take-Two Interactive',       sector: 'Oyun',             indices: ['NDX'] },

  // --- Enerji / Sanayi / Malzeme -------------------------------------------
  { ticker: 'XOM',   name: 'ExxonMobil',                sector: 'Enerji',           indices: ['SPX'] },
  { ticker: 'CVX',   name: 'Chevron',                   sector: 'Enerji',           indices: ['SPX'] },
  { ticker: 'BKR',   name: 'Baker Hughes',              sector: 'Enerji Ekipmanı',  indices: ['NDX'] },
  { ticker: 'FANG',  name: 'Diamondback Energy',        sector: 'Enerji (Şeyl)',    indices: ['NDX'] },
  { ticker: 'LIN',   name: 'Linde',                     sector: 'Kimya/Endüstriyel Gaz', indices: ['NDX'] },
  { ticker: 'CAT',   name: 'Caterpillar',                sector: 'Ağır Makine',      indices: ['SPX'] },
  { ticker: 'DE',    name: 'Deere & Company',           sector: 'Tarım Makinesi',   indices: ['SPX'] },
  { ticker: 'GE',    name: 'GE Aerospace',              sector: 'Havacılık',        indices: ['SPX'] },
  { ticker: 'RTX',   name: 'RTX Corp (Raytheon)',       sector: 'Savunma/Havacılık', indices: ['SPX'] },
  { ticker: 'LMT',   name: 'Lockheed Martin',           sector: 'Savunma',          indices: ['SPX'] },
  { ticker: 'BA',    name: 'Boeing',                    sector: 'Havacılık',        indices: ['SPX'] },
  { ticker: 'UNP',   name: 'Union Pacific',              sector: 'Demiryolu',        indices: ['SPX'] },
  { ticker: 'UPS',   name: 'United Parcel Service',     sector: 'Lojistik',         indices: ['SPX'] },
  { ticker: 'EMR',   name: 'Emerson Electric',          sector: 'Sanayi Otomasyon', indices: ['SPX'] },
  { ticker: 'GM',    name: 'General Motors',            sector: 'Otomotiv',         indices: ['SPX'] },
  { ticker: 'F',     name: 'Ford Motor',                sector: 'Otomotiv',         indices: ['SPX'] },
  { ticker: 'TSLA',  name: 'Tesla',                     sector: 'Otomotiv/Enerji',  indices: ['NDX', 'SPX'] },
  { ticker: 'ENPH',  name: 'Enphase Energy',            sector: 'Güneş Enerjisi',   indices: ['NDX'] },

  // --- Telekom / Utilities / GYO --------------------------------------------
  { ticker: 'T',     name: 'AT&T',                      sector: 'Telekom',          indices: ['SPX'] },
  { ticker: 'VZ',    name: 'Verizon Communications',    sector: 'Telekom',          indices: ['SPX'] },
  { ticker: 'NEE',   name: 'NextEra Energy',            sector: 'Elektrik/Yenilenebilir', indices: ['SPX'] },
  { ticker: 'DUK',   name: 'Duke Energy',               sector: 'Elektrik Dağıtım', indices: ['SPX'] },
  { ticker: 'SO',    name: 'Southern Company',           sector: 'Elektrik Dağıtım', indices: ['SPX'] },
  { ticker: 'AEP',   name: 'American Electric Power',   sector: 'Elektrik Dağıtım', indices: ['NDX'] },
  { ticker: 'EXC',   name: 'Exelon',                    sector: 'Elektrik Dağıtım', indices: ['NDX'] },
  { ticker: 'XEL',   name: 'Xcel Energy',               sector: 'Elektrik Dağıtım', indices: ['NDX'] },
  { ticker: 'PLD',   name: 'Prologis',                  sector: 'GYO (Lojistik)',   indices: ['SPX'] },
  { ticker: 'EQIX',  name: 'Equinix',                   sector: 'GYO (Veri Merkezi)', indices: ['SPX'] },

  // --- Danışmanlık / Bilgi Hizmetleri ---------------------------------------
  { ticker: 'BRK.B', name: 'Berkshire Hathaway (B)',    sector: 'Holding/Sigorta',  indices: ['SPX'], symbol: 'BRK-B' },
  { ticker: 'CTSH',  name: 'Cognizant Technology',      sector: 'BT Hizmetleri',    indices: ['NDX'] },
  { ticker: 'WBA',   name: 'Walgreens Boots Alliance',  sector: 'Eczane Zinciri',   indices: ['NDX'] },
];

export function toUsSymbol(ticker, override) {
  return override || ticker;
}
